name: Enterprise Builder Quality Gates

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '22'

jobs:
  # ── GATE Phase 1: Enterprise Context Validation ─────────────────────────
  validate-context:
    name: "Gate 1 — Enterprise Context"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check enterprise context document
        run: |
          if [ ! -f "docs/enterprise-context.md" ]; then
            echo "❌ Phase 1 incomplete: missing docs/enterprise-context.md"
            echo "   Run METHOD-ENTERPRISE-BUILDER-PLANNING Phase 1 to generate it."
            exit 1
          fi
          echo "✅ Enterprise context document found"

      - name: Verify required sections in context
        run: |
          MISSING=0
          for section in "System Classification" "Stakeholder Map" "Regulatory Environment" "Integration Points"; do
            if ! grep -q "$section" docs/enterprise-context.md; then
              echo "❌ Missing section: $section"
              MISSING=1
            fi
          done
          [ $MISSING -eq 0 ] && echo "✅ All required sections present"
          exit $MISSING

  # ── GATE Phase 3: Risk Matrix Validation ────────────────────────────────
  validate-risks:
    name: "Gate 3 — Risk Matrix"
    runs-on: ubuntu-latest
    needs: validate-context
    steps:
      - uses: actions/checkout@v4

      - name: Check STRIDE analysis document
        run: |
          STRIDE_FILES=$(find docs -name "*stride*" -o -name "*risk*" 2>/dev/null | wc -l)
          if [ "$STRIDE_FILES" -eq 0 ]; then
            echo "❌ Phase 3 incomplete: no STRIDE/risk analysis document found in docs/"
            exit 1
          fi
          echo "✅ Risk analysis document found ($STRIDE_FILES file(s))"

      - name: Check for unmitigated critical risks
        run: |
          RISK_FILES=$(find docs -name "*risk*" -o -name "*stride*" 2>/dev/null)
          if echo "$RISK_FILES" | xargs grep -li "critical.*unmitigated\|unmitigated.*critical" 2>/dev/null; then
            echo "❌ Unmitigated critical risks detected — all critical risks must have mitigations"
            exit 1
          fi
          echo "✅ No unmitigated critical risks detected"

  # ── GATE Phase 5: ADR Validation ────────────────────────────────────────
  validate-adrs:
    name: "Gate 5 — ADR Validation"
    runs-on: ubuntu-latest
    needs: validate-context
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run ADR Validator
        run: |
          mkdir -p reports
          if [ ! -d "docs/adr" ] || [ -z "$(ls -A docs/adr/*.md 2>/dev/null)" ]; then
            echo "⚠️  No ADRs found in docs/adr/ — skipping validation"
            exit 0
          fi
          node --experimental-strip-types \
            packs/enterprise-architecture-pack/validators/adr-validator/src/index.ts \
            --format=junit \
            --output=reports/adr-validation.xml \
            docs/adr/

      - name: Upload ADR validation report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: adr-validation
          path: reports/adr-validation.xml

  # ── GATE Phase 7: Test Quality Gate ─────────────────────────────────────
  test-quality-gate:
    name: "Gate 7 — Tests & Coverage ≥99%"
    runs-on: ubuntu-latest
    needs: [validate-risks, validate-adrs]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - run: npm ci

      - name: Run unit tests with coverage
        run: npm test -- --coverage --reporter=json --outputFile=reports/test-results.json

      - name: Validate coverage ≥99%
        run: bash .ci-cd/scripts/coverage-check.sh --threshold=99

      - name: Run microtask line linter
        run: bash .ci-cd/scripts/microtask-lint.sh --dir=src --max-lines=50

      - name: Run integration tests
        run: npm run test:integration || echo "⚠️  No integration test script found"

      - name: Upload test evidence
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-evidence
          path: |
            reports/
            coverage/

  # ── GATE Phase 8: Delivery Validation ───────────────────────────────────
  validate-delivery:
    name: "Gate 8 — Delivery Sign-off"
    runs-on: ubuntu-latest
    needs: test-quality-gate
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: reports

      - name: Run delivery gate
        run: bash .ci-cd/scripts/validate-delivery.sh

      - name: Create delivery evidence archive
        uses: actions/upload-artifact@v4
        with:
          name: delivery-evidence-${{ github.sha }}
          path: reports/
          retention-days: 90
